export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// User Authentication Types
export const USER_LOADED = 'USER_LOADED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

// Admin Types
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';
export const CHECK_CURRENT_PASSWORD_SUCCESS = 'CHECK_CURRENT_PASSWORD_SUCCESS';
export const CHECK_CURRENT_PASSWORD_ERROR = 'CHECK_CURRENT_PASSWORD_ERROR';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const APPROVE_USER_SUCCESS = 'APPROVE_USER_SUCCESS';
export const APPROVE_USER_ERROR = 'APPROVE_USER_ERROR';

// User Types
export const GET_ALL_USER_CONTACTS = 'GET_ALL_USER_CONTACTS';
export const GET_ALL_USER_CONTACTS_ERROR = 'GET_ALL_USER_CONTACTS_ERROR';
export const GET_ALL_ACTIVE_USERS = 'GET_ALL_ACTIVE_USERS';
export const GET_ALL_ACTIVE_USERS_ERROR = 'GET_ALL_ACTIVE_USERS_ERROR';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_ERROR = 'ADD_CONTACT_ERROR';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_ERROR = 'UPDATE_CONTACT_ERROR';
export const DELETE_USER_CONTACT_SUCCESS = 'DELETE_USER_CONTACT_SUCCESS';
export const DELETE_USER_CONTACT_ERROR = 'DELETE_USER_CONTACT_ERROR';
export const SHARED_CONTACTS_WITH_SUCCESS = 'SHARED_CONTACTS_WITH_SUCCESS';
export const SHARED_CONTACTS_WITH_ERROR = 'SHARED_CONTACTS_WITH_ERROR';
export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';
export const CLEAR_USERS = 'CLEAR_USERS';
